# Generated by Django 2.2.6 on 2019-11-01 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('booking_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('round_date', models.DateField(db_index=True, verbose_name='Round day')),
                ('round_time', models.TimeField(verbose_name='Round time')),
                ('pax', models.IntegerField(default=4, verbose_name='Pax')),
                ('hole', models.IntegerField(choices=[(0, '18 Holes'), (1, '9 Holes'), (2, '27 Holes'), (3, '36 Holes')], db_index=True, default=0, verbose_name='No. of holes')),
                ('green_fee_sales', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Green fee sales')),
                ('cart_fee_sales', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Cart fee sales')),
                ('caddie_fee_sales', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Caddie fee sales')),
                ('green_fee_pay_on_arrival', models.BooleanField(db_index=True, default=False, verbose_name='Green fee pay on arrival')),
                ('cart_fee_pay_on_arrival', models.BooleanField(db_index=True, default=False, verbose_name='Cart fee pay on arrival')),
                ('caddie_fee_pay_on_arrival', models.BooleanField(db_index=True, default=False, verbose_name='Caddie fee pay on arrival')),
                ('green_fee_cost', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Green fee cost')),
                ('cart_fee_cost', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Cart fee cost')),
                ('cart_fee_deducted_from_deposit', models.IntegerField(default=0, verbose_name='Cart fee deducted from deposit')),
                ('caddie_fee_cost', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Caddie fee cost')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full name')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='Memo')),
                ('season', models.IntegerField(choices=[(0, 'Low season'), (1, 'High season')], db_index=True, default=1, verbose_name='High/Low Season')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Weekday'), (1, 'Weekend')], db_index=True, default=0, verbose_name='Day of week')),
                ('slot', models.IntegerField(choices=[(0, 'Morning'), (1, 'Daytime'), (2, 'Twilight'), (3, 'Night')], db_index=True, default=0, verbose_name='Time slot')),
                ('status', models.IntegerField(choices=[(0, 'order opened'), (1, 'order pending'), (2, 'payment pending'), (3, 'order complete'), (4, 'order offered'), (5, 'order voided'), (6, 'refund requested'), (7, 'refund pending'), (8, 'order refunded(original)'), (9, 'order refunded(reverse)')], db_index=True, default=0, verbose_name='Booking status')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='GolfClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Golf club name')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Golf club code')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email address')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('hole', models.IntegerField(choices=[(0, '18 Holes'), (1, '9 Holes'), (2, '27 Holes'), (3, '36 Holes')], db_index=True, default=0, verbose_name='No. of holes')),
                ('cart_fee', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Cart fee')),
                ('caddie_fee', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Caddie fee')),
                ('high_season', models.IntegerField(default=3075, verbose_name='High season')),
                ('max_high_weekday', models.PositiveIntegerField(default=0, verbose_name='Max # of High/Weekday')),
                ('max_high_weekend', models.PositiveIntegerField(default=0, verbose_name='Max # of High/Weekend')),
                ('max_low_weekday', models.PositiveIntegerField(default=0, verbose_name='Max # of Low/Weekday')),
                ('max_low_weekend', models.PositiveIntegerField(default=0, verbose_name='Max # of Low/Weekend')),
                ('country', models.IntegerField(choices=[(1, 'Thailand'), (2, 'South Korea'), (3, 'Japan'), (4, 'China')], db_index=True, default=1, verbose_name='Country code')),
            ],
            options={
                'verbose_name': 'Golf club',
                'verbose_name_plural': 'Golf clubs',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Holiday name')),
                ('holiday', models.DateField(db_index=True, verbose_name='Holiday date')),
                ('country', models.IntegerField(choices=[(1, 'Thailand'), (2, 'South Korea'), (3, 'Japan'), (4, 'China')], db_index=True, default=1, verbose_name='Country code')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'unique_together': {('holiday', 'country')},
            },
        ),
        migrations.CreateModel(
            name='BookingTeeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('tee_off_time', models.TimeField(blank=True, null=True, verbose_name='Tee off time')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.Booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Booking tee-off',
                'verbose_name_plural': 'Booking tee-off',
            },
        ),
    ]
