# Generated by Django 2.2.6 on 2019-10-31 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('booking_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('round_date', models.DateField(db_index=True, verbose_name='Round day')),
                ('round_time', models.TimeField(verbose_name='Round time')),
                ('tee_off_time', models.TimeField(blank=True, null=True, verbose_name='Tee off time')),
                ('pax', models.IntegerField(verbose_name='Pax')),
                ('green_fee_sales', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Green fee sales')),
                ('cart_fee_sales', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Cart fee sales')),
                ('caddie_fee_sales', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Caddie fee sales')),
                ('green_fee_cost', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Green fee cost')),
                ('cart_fee_cost', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Cart fee cost')),
                ('caddie_fee_cost', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Caddie fee cost')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full name')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='Memo')),
                ('season', models.IntegerField(choices=[(0, 'Low season'), (1, 'High season')], db_index=True, default=1, verbose_name='High/Low Season')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Weekday'), (1, 'Weekend')], db_index=True, default=0, verbose_name='Day of week')),
                ('slot', models.IntegerField(choices=[(0, 'Morning'), (1, 'Daytime'), (2, 'Twilight'), (3, 'Night')], db_index=True, default=0, verbose_name='Time slot')),
                ('status', models.IntegerField(choices=[(0, 'order opened'), (1, 'order pending'), (2, 'payment pending'), (3, 'order complete'), (4, 'order offered'), (5, 'order voided'), (6, 'refund requested'), (7, 'refund pending'), (8, 'order refunded(original)'), (9, 'order refunded(reverse)')], db_index=True, default=0, verbose_name='Booking status')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
            },
        ),
    ]
