# Generated by Django 2.2.6 on 2019-11-03 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='round_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Round time'),
            preserve_default=False,
        ),
    ]
