# Generated by Django 2.2.6 on 2019-11-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='agent',
            new_name='requester',
        ),
    ]
