# Generated by Django 2.2.6 on 2019-10-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday',
            field=models.DateField(db_index=True, verbose_name='Holiday date'),
        ),
    ]
