# Generated by Django 2.2.6 on 2019-11-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='round_time',
        ),
    ]
