# Generated by Django 2.2.6 on 2019-10-23 06:44

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20191022_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Golf club name')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email address')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('hole', models.IntegerField(choices=[(0, '18 Holes'), (1, '9 Holes'), (2, '27 Holes'), (3, '36 Holes')], db_index=True, default=0, verbose_name='No. of holes')),
                ('cart_fee', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Cart fee')),
                ('caddie_fee', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Caddie fee')),
                ('high_season', models.IntegerField(default=3075, verbose_name='High season')),
                ('max_high_weekday', models.PositiveIntegerField(default=0, verbose_name='Max # of High/Weekday')),
                ('max_high_weekend', models.PositiveIntegerField(default=0, verbose_name='Max # of High/Weekend')),
                ('max_low_weekday', models.PositiveIntegerField(default=0, verbose_name='Max # of Low/Weekday')),
                ('max_low_weekend', models.PositiveIntegerField(default=0, verbose_name='Max # of Low/Weekend')),
                ('country', models.IntegerField(choices=[(1, 'Thailand'), (2, 'South Korea'), (3, 'Japan'), (4, 'China')], db_index=True, default=1, verbose_name='Country code')),
            ],
            options={
                'verbose_name': 'Golf club',
                'verbose_name_plural': 'Golf clubs',
            },
        ),
    ]
