# Generated by Django 2.2.6 on 2019-11-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20191101_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hole',
            field=models.IntegerField(choices=[(0, '18 Holes'), (1, '9 Holes'), (2, '27 Holes'), (3, '36 Holes')], db_index=True, default=0, verbose_name='No. of holes'),
        ),
    ]
