# Generated by Django 2.2.6 on 2019-10-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='caddie_fee_pay_on_arrival',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Caddie fee pay on arrival'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cart_fee_pay_on_arrival',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Cart fee pay on arrival'),
        ),
        migrations.AddField(
            model_name='booking',
            name='green_fee_pay_on_arrival',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Green fee pay on arrival'),
        ),
    ]
