# Generated by Django 2.2.6 on 2019-11-01 05:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_remove_booking_round_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='caddie_fee_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='THB', max_digits=11, verbose_name='Caddie fee sales'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cart_fee_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='THB', max_digits=11, verbose_name='Cart fee cost'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cart_fee_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='THB', max_digits=11, verbose_name='Cart fee sales'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='green_fee_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='THB', max_digits=11, verbose_name='Green fee cost'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='green_fee_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='THB', max_digits=11, verbose_name='Green fee sales'),
        ),
    ]
