# Generated by Django 2.2.6 on 2019-10-31 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20191031_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requester'),
        ),
    ]
