# Generated by Django 2.2.6 on 2019-11-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20191101_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='fullname',
        ),
    ]
