# Generated by Django 2.2.6 on 2019-11-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_booking_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cart_fee_deducted_from_deposit',
            field=models.IntegerField(default=0, verbose_name='Cart fee deducted from deposit'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pax',
            field=models.IntegerField(default=4, verbose_name='Pax'),
        ),
    ]
