# Generated by Django 2.2.6 on 2019-10-31 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20191031_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tee_off_time',
        ),
        migrations.CreateModel(
            name='BookingTeeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('tee_off_time', models.TimeField(blank=True, null=True, verbose_name='Tee off time')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.Booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Booking tee-off',
                'verbose_name_plural': 'Booking tee-off',
            },
        ),
    ]
