# Generated by Django 2.2.6 on 2019-10-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20191023_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='code',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Golf club code'),
            preserve_default=False,
        ),
    ]
