# Generated by Django 2.2.6 on 2019-11-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_remove_booking_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Mr.'), (1, 'Ms.')], db_index=True, default=0, verbose_name='Gender'),
        ),
    ]
