# Generated by Django 2.2.6 on 2019-11-02 14:08

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0005_booking_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('round_date', models.DateField(db_index=True, verbose_name='Round day')),
                ('tee_off_time', models.TimeField(blank=True, null=True, verbose_name='Tee off time')),
            ],
            options={
                'verbose_name': 'Tee-off',
                'verbose_name_plural': 'Tee-off',
            },
        ),
    ]
