# Generated by Django 2.2.6 on 2019-11-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0006_teeoff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teeoff',
            unique_together={('round_date', 'tee_off_time')},
        ),
    ]
