# Generated by Django 2.2.6 on 2019-11-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0007_auto_20191102_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stand_by',
            field=models.BooleanField(default=False, verbose_name='Stand-by'),
        ),
        migrations.AddField(
            model_name='teeoff',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='teeoff',
            name='staff',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Golf club staff'),
        ),
    ]
